openapi: 3.2.0
info:
  version: 1.37.0
  title: Harver Public Candidate Statuses API
  description: Public API of the Harver Platform available only for the Customers of Harver.
  contact:
    name: Harver Support Team
    email: support@harver.com
    url: https://support.harver.com
servers:
- url: https://api.harver.com/api/v1.0/
  description: Production Server
tags:
- name: candidate-statuses
paths:
  /candidate-statuses:
    get:
      summary: Returns the available candidate statuses
      tags:
      - candidate-statuses
      responses:
        '200':
          description: An array of Candidate Statuses
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                minProperties: 1
                properties:
                  data:
                    type: array
                    items:
                      properties:
                        type:
                          type: string
                          example: status
                        id:
                          type: string
                        attributes:
                          properties:
                            label:
                              type: string
      operationId: getCandidateStatuses
      x-operation-id-source: derived
